-- 아직 입양을 못 간 동물 = O 테이블 레코드가 NULL인 동물
SELECT NAME, DATETIME
FROM (SELECT I.NAME, I.DATETIME
    FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.ANIMAL_ID IS NULL
    ORDER BY 2
)
WHERE ROWNUM <= 3;